env:
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]
        rust: [stable, nightly]
        include:
          - os: ubuntu-24.04
            rust: beta
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - run: cargo test
      - run: cargo doc
